version: '3.4'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
    command: >
      sh -c "dotnet ef database update && dotnet run"
